# Generated by Django 5.0.1 on 2024-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_talaba_kitob_soni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='tugilgan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
